apps/libros/urls.py
from django.urls import path
from apps.libros.views import autorCreate, autorEdit, autorElim, libroCreate, libroEdit, libroElim, listAutores, listLibros


app_name= 'libros'
urlpatterns = [
    path('', listLibros, name = 'listLibros'),
    path('nuevol/', libroCreate, name = 'libroCreate'),
    path('actualizarl/<int:id_libro>/', libroEdit, name='libroEdit'),
    path('eliminarl/<int:id_libro>/', libroElim, name='libroElim'),

    ##### Autor #####
    path('autores', listAutores, name = 'listAutores'),
    path('nuevoa/', autorCreate, name = 'autorCreate'),
    path('actualizara/<int:id_autor>/', autorEdit, name='autorEdit'),
    path('eliminara/<int:id_autor>/', autorElim, name='autorElim'),

]

apps/prestar/urls.py
from django.urls import path

from apps.prestar.views import consulta1, consulta2, consulta3, ejemplarCreate, ejemplarEdit, ejemplarElim, listEjemplar, listUsuario, listprestar, prestarCreate, prestarEdit, prestarElim, usuarioCreate, usuarioEdit, usuarioElim

app_name= 'prestar'
urlpatterns = [
    path('', listprestar, name = 'listprestar'),
    path('nuevop/', prestarCreate, name = 'prestarCreate'),
    path('actualizarp/<int:id_prestar>/', prestarEdit, name='prestarEdit'),
    path('eliminarp/<int:id_prestar>/', prestarElim, name='prestarElim'),

    ######### Usuario ############

    path('usuarios', listUsuario, name = 'listUsuario'),
    path('nuevou/', usuarioCreate, name = 'usuarioCreate'),
    path('actualizaru/<int:id_usuario>/', usuarioEdit, name='usuarioEdit'),
    path('eliminaru/<int:id_usuario>/', usuarioElim, name='usuarioElim'),

    ######### Ejemplar #############

    path('ejemplares', listEjemplar, name = 'listEjemplar'),
    path('nuevoe/', ejemplarCreate, name = 'ejemplarCreate'),
    path('actualizare/<int:id_ejemplar>/', ejemplarEdit, name='ejemplarEdit'),
    path('eliminare/<int:id_ejemplar>/', ejemplarElim, name='ejemplarElim'),


############ Consultas ###############
    path('consulta1', consulta1, name = 'consulta1'),
    path('consulta2', consulta2, name = 'consulta2'),
    path('consulta3', consulta3, name = 'consulta3'),




]

pryprestamos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.prestar.views import home

urlpatterns = [
    path('', home, name= 'home'),
    path('admin/', admin.site.urls),
    path('prestar/', include('apps.prestar.urls', namespace="prestar")),
    path('libros/', include('apps.libros.urls', namespace="libros")),

]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'home' %}">Inicio
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'prestar:listprestar' %}">Prestamos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'libros:listLibros' %}">Libros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'libros:listAutores' %}">Autores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'prestar:listUsuario' %}">Usuarios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'prestar:listEjemplar' %}">Ejemplares</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Consultas</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'prestar:consulta1' %}">Consulta 1</a>
                  <a class="dropdown-item" href="{% url 'prestar:consulta2' %}">Consulta 2</a>
                  <a class="dropdown-item" href="{% url 'prestar:consulta3' %}">Consulta 3</a>
                </div>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-sm-2" type="text" placeholder="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock %}

      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>