apps/prestar/urls.py
from django.urls import path

from apps.prestar.views import consulta1, consulta2, consulta3, ejemplarCreate, ejemplarEdit, ejemplarElim, listEjemplar, listUsuario, listprestar, prestarCreate, prestarEdit, prestarElim, usuarioCreate, usuarioEdit, usuarioElim

app_name= 'prestar'
urlpatterns = [
    path('', listprestar, name = 'listprestar'),
    path('nuevop/', prestarCreate, name = 'prestarCreate'),
    path('actualizarp/<int:id_prestar>/', prestarEdit, name='prestarEdit'),
    path('eliminarp/<int:id_prestar>/', prestarElim, name='prestarElim'),

    ######### Usuario ############

    path('usuarios', listUsuario, name = 'listUsuario'),
    path('nuevou/', usuarioCreate, name = 'usuarioCreate'),
    path('actualizaru/<int:id_usuario>/', usuarioEdit, name='usuarioEdit'),
    path('eliminaru/<int:id_usuario>/', usuarioElim, name='usuarioElim'),

    ######### Ejemplar #############

    path('ejemplares', listEjemplar, name = 'listEjemplar'),
    path('nuevoe/', ejemplarCreate, name = 'ejemplarCreate'),
    path('actualizare/<int:id_ejemplar>/', ejemplarEdit, name='ejemplarEdit'),
    path('eliminare/<int:id_ejemplar>/', ejemplarElim, name='ejemplarElim'),


############ Consultas ###############
    path('consulta1', consulta1, name = 'consulta1'),
    path('consulta2', consulta2, name = 'consulta2'),
    path('consulta3', consulta3, name = 'consulta3'),




]

pryprestamos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.prestar.views import home

urlpatterns = [
    path('', home, name= 'home'),
    path('admin/', admin.site.urls),
    path('prestar/', include('apps.prestar.urls', namespace="prestar")),
    path('libros/', include('apps.libros.urls', namespace="libros")),

]

templates/usuarios/listUsuario.html
{% extends 'base/base.html' %}


{% block content %}
    

    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3> Listado de usuarios </h3>
            </div>

            <div class="col-4">

            </div>

            <div class="col-4">
                <a href="{% url 'prestar:usuarioCreate' %}" class="btn btn-primary pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>
        
    </h1>

    <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Direccion</th>
            <th scope="col">Telefono</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>
            {% if usuarios %}
            {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.nombre }}</td>
                    <td>{{ usuario.apellidos }}</td>
                    <td>{{ usuario.direccion }}</td>
                    <td>{{ usuario.telefono }}</td>
                    <td class="d-flex justify-content-center">
                        <a class="btn btn-primary btn-warning btn-xs" href="{% url 'prestar:usuarioEdit' usuario.id %}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
  
                        <a class="btn btn-primary btn-dange btn-xs" href="{% url 'prestar:usuarioElim' usuario.id %}">
                            <i class="fa-solid fa-trash-can"></i>
                        </a>
                </tr>
            {% endfor %}
          {% else %}
              <h3>No existen registros</h3>
           {% endif %}
        </tbody>
      </table>
    
{% endblock %}

templates/usuarios/usuarioElimform.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Desea eliminar el registro: {{ usuarios.nombre }}</h3>
    <button class="btn btn-danger" type="submit">
        Si, Eliminar
    </button>
    <a href="{% url 'prestar:listUsuario' %}" class="btn btn-primary">Cancelar</a>
</form>
{% endblock  %}

templates/usuarios/usuario_form.html
{% extends 'base/base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">
            Guardar Datos
        </button>
    </form>
{% endblock %}