apps/libros/urls.py
from django.urls import path
from apps.libros.views import autorCreate, autorEdit, autorElim, libroCreate, libroEdit, libroElim, listAutores, listLibros


app_name= 'libros'
urlpatterns = [
    path('', listLibros, name = 'listLibros'),
    path('nuevol/', libroCreate, name = 'libroCreate'),
    path('actualizarl/<int:id_libro>/', libroEdit, name='libroEdit'),
    path('eliminarl/<int:id_libro>/', libroElim, name='libroElim'),

    ##### Autor #####
    path('autores', listAutores, name = 'listAutores'),
    path('nuevoa/', autorCreate, name = 'autorCreate'),
    path('actualizara/<int:id_autor>/', autorEdit, name='autorEdit'),
    path('eliminara/<int:id_autor>/', autorElim, name='autorElim'),

]

pryprestamos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.prestar.views import home

urlpatterns = [
    path('', home, name= 'home'),
    path('admin/', admin.site.urls),
    path('prestar/', include('apps.prestar.urls', namespace="prestar")),
    path('libros/', include('apps.libros.urls', namespace="libros")),

]

templates/autores/autorElimform.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Desea eliminar el registro: {{ autor.nombre }}</h3>
    <button class="btn btn-danger" type="submit">
        Si, Eliminar
    </button>
    <a href="{% url 'libros:listAutores' %}" class="btn btn-primary">Cancelar</a>
</form>
{% endblock  %}

templates/autores/autor_form.html
{% extends 'base/base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">
            Guardar Datos
        </button>
    </form>
{% endblock %}

templates/autores/listAutores.html
{% extends 'base/base.html' %}


{% block content %}
    

    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3> Listado de autores </h3>
            </div>

            <div class="col-4">

            </div>

            <div class="col-4">
                <a href="{% url 'libros:autorCreate' %}" class="btn btn-primary pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>
        
    </h1>

    <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Opciones</th>
          </tr>
        </thead>
        <tbody>
            {% if autores %}
            {% for autor in autores %}
                <tr>
                    <td>{{ autor.nombre }}</td>
                    <td class="d-flex justify-content-center">
                        <a class="btn btn-primary btn-warning btn-xs" href="{% url 'libros:autorEdit' autor.id %}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
  
                        <a class="btn btn-primary btn-dange btn-xs" href="{% url 'libros:autorElim' autor.id %}">
                            <i class="fa-solid fa-trash-can"></i>
                        </a>
                </tr>
            {% endfor %}
          {% else %}
              <h3>No existen registros</h3>
           {% endif %}
        </tbody>
      </table>
    
{% endblock %}